name: Ejecutar v_2_APITESTfinal automáticamente

on:
  schedule:
    - cron: "0 12 * * *"  # 9:00 AM Argentina (UTC-3 → 12:00 UTC)
  workflow_dispatch:        # Permite ejecución manual

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install jupyter nbconvert
          pip install -r requirements.txt || echo "No hay requirements.txt, continuando..."

      - name: Ejecutar notebook
        run: |
          jupyter nbconvert --to notebook --execute v_2_APITESTfinal.ipynb --output resultado_ejecucion.ipynb
